# This Lakefile is only a convenience one to be able to build any of the sub-projects from this
# directory.  This doesn't build anything, but it lets you run e.g.
#
# lake build ./zkLean/zkLean.lean
#
# to build zkLean specifically.

name = "zkLeanEcosystem"

[[require]]
name = "BVModEq"
path = "./bvmod_eq"

[[require]]
name = "zkLean"
path = "./zkLean"

[[require]]
name = "zkLeanExamples"
path = "./examples"
