# This Lakefile is only a convenience one to be able to build any of the sub-projects from this
# directory.  This doesn't build anything, but it lets you run e.g.
#
# lake build ./zk_lean/ZKLean.lean
#
# to build ZKLean specifically.

name = "ZKLeanEcosystem"

[[require]]
name = "BVModEq"
path = "./bvmod_eq"

[[require]]
name = "ZKLean"
path = "./zk_lean"

[[require]]
name = "ZKLeanExamples"
path = "./zk_lean_examples"
