name = "bvmod_eq"
version = "0.0.1"
defaultTargets = ["bvmod_eq"]

[[lean_lib]]
name = "BvMod_eq"

[[lean_exe]]
name = "bvmod_eq"
root = "BvMod_eq"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"
