name = "zkLean"
version = "0.1.0"
defaultTargets = ["zkLeanMain"]

[[lean_lib]]
name = "zkLean"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.2"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.25.1" # Note: they did not make a 4.25.2 release yet

[[require]]
name = "BVModEq"
path = "../bvmod_eq"
