name = "zkLean"
version = "0.1.0"
defaultTargets = ["zkLeanMain"]

[[lean_lib]]
name = "zkLean"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0-rc1"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.28.0-rc1"

[[require]]
name = "BVModEq"
path = "../bvmod_eq"
