name = "ZKLean"
version = "0.1.0"
defaultTargets = ["ZKLeanMain"]

[[lean_lib]]
name = "ZKLean"

[[lean_exe]]
name = "ZKLeanMain"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "BVModEq"
path = "../bvmod_eq"
