name = "ZKLeanExamples"
version = "0.0.1"
defaultTargets = ["ZKLeanExamplesMain"]

[[lean_lib]]
name = "ZKLeanExamples"

[[lean_exe]]
name = "ZKLeanExamplesMain"
root = "ZKLeanExamples"

[[require]]
name = "BVModEq"
path = "../bvmod_eq"

[[require]]
name = "ZKLean"
path = "../zk_lean"
